# Generated by Django 4.1.7 on 2023-04-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='game',
            field=models.ManyToManyField(related_name='game_user', to='api.game'),
        ),
    ]
