# Generated by Django 4.1.7 on 2023-04-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_stage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='game',
            field=models.ManyToManyField(default=None, related_name='game_user', to='api.game'),
        ),
    ]
