# Generated by Django 4.1.7 on 2023-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_gameuser_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='game',
            field=models.ManyToManyField(related_name='game_user', to='api.game'),
        ),
    ]
