# Generated by Django 4.1.7 on 2023-04-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_gameuser_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='game',
            field=models.ManyToManyField(related_name='game_user', to='api.game', verbose_name='игры'),
        ),
    ]
